blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://github.com/LenovoLegionToolkit-Team/LenovoLegionToolkit/discussions/new?category=q-a
    about: Please ask questions here.
